config/routes.rb
Davesblog::Application.routes.draw do
  resources :blog_images

  resources :site_settings

  resources :categories

  resources :tags

  match 'blogs/fix_blank_published_dates' => 'blogs#fix_blank_published_dates'
  resources :blogs

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  match '/:id' => 'blogs#show'
  
  match "user/settings" => "user#settings"
  match 'user/update' => 'user#update', :as=>'user/update', :via=>'put'

  

  root :to => 'blogs#index'

end

app/models/site_setting.rb
class SiteSetting < ActiveRecord::Base
end

app/controllers/site_settings_controller.rb
class SiteSettingsController < ApplicationController
before_filter :authenticate_user!
  # GET /site_settings
  # GET /site_settings.json
  def index
    @site_settings = SiteSetting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @site_settings }
    end
  end

  # GET /site_settings/1
  # GET /site_settings/1.json
  def show
  	if current_user.is_admin==1
		@site_setting = SiteSetting.find(params[:id])
	
		respond_to do |format|
		  format.html # show.html.erb
		  format.json { render json: @site_setting }
		end
    end
  end

  # GET /site_settings/new
  # GET /site_settings/new.json
  def new
  	if current_user.is_admin==1
    @site_setting = SiteSetting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site_setting }
    end
    end
  end

  # GET /site_settings/1/edit
  def edit
    @site_setting = SiteSetting.find(params[:id])
    @categories=Category.all
  end

  # POST /site_settings
  # POST /site_settings.json
  def create
    if current_user.is_admin==1
    @site_setting = SiteSetting.new(params[:site_setting])

    respond_to do |format|
      if @site_setting.save
        format.html { redirect_to @site_setting, notice: 'Site settings were successfully created.' }
        format.json { render json: @site_setting, status: :created, location: @site_setting }
      else
        format.html { render action: "new" }
        format.json { render json: @site_setting.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # PUT /site_settings/1
  # PUT /site_settings/1.json
  def update
  	if current_user.is_admin==1
    @site_setting = SiteSetting.find(params[:id])

    respond_to do |format|
      if @site_setting.update_attributes(params[:site_setting])
        format.html { redirect_to :action=> :edit, notice: 'Site settings were successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site_setting.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /site_settings/1
  # DELETE /site_settings/1.json
  def destroy
  	if current_user.is_admin==1
    @site_setting = SiteSetting.find(params[:id])
    @site_setting.destroy

    respond_to do |format|
      format.html { redirect_to site_settings_url }
      format.json { head :no_content }
    end
  end
  end
end

app/helpers/site_settings_helper.rb
module SiteSettingsHelper
end

app/views/site_settings/_form.html.erb
<%= form_for(@site_setting) do |f| %>
  <% if @site_setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_setting.errors.count, "error") %> prohibited this site_setting from being saved:</h2>

      <ul>
      <% @site_setting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br/><br/>

<div class="actions">
    <%= f.submit value="Update Settings", :class=> 'btn btn-primary' %><a class="btn btn-primary" href="<%= '/user/settings/' %>">Back</a>
  </div>
  <div class="field">
    Enable/Disable Caching: <%= f.check_box(:caching, options = {}, checked_value = "1", unchecked_value = "0") %>
  </div>
  
  <div class="field">
    Site Name: <%= f.text_field :site_name %>
  </div>
  <div class="field">
    Default Time Zone: <%= time_zone_select("site_setting", "time_zone", nil, :default => "Pacific Time (US & Canada)" ) %>
  </div>
  <div class="field">
  	Menubar Categories - comman seperated (leave empty to show all) <%= f.text_field :menu_categories, :placeholder=> 'eg: 1,2,3' %>
  <br/>
  Category id's: <% @categories.each do |cat| %><%= cat.name %>:<%= cat.id %>,<% end %>
  </div>
  <div class="field">
    Left Sidebar (Use HTML Code)<br />
    <%= f.text_area :left_sidebar %>
  </div>
    <div class="field">
    Disqus (or other comment system) code<br />
    <%= f.text_area :disqus_code %>
  </div>
      <div class="field">
    Analytics Code (Like Google Analytics)<br />
    <%= f.text_area :analytics %>
  </div>
      <div class="field">
    Google Plus One code<br />
    <%= f.text_area :plusone %>
  </div>
      <div class="field">
    Facebook Like Code<br />
    <%= f.text_area :facebook %>
  </div>
        <div class="field">
    Sharethis code<br />
    <%= f.text_area :sharethis %>
  </div>
        <div class="field">
    Sharethis Mobile code<br />
    <%= f.text_area :sharethis_mobile %>
  </div>
        <div class="field">
    Sharethis Header Code<br />
    <%= f.text_area :sharethis_head %>
  </div>
<% end %>

app/views/site_settings/edit.html.erb
<% content_for :title, "Site Settings -> "+@settings.site_name.to_s %>
<div class="span1">&nbsp;</div><div class="span1">&nbsp;</div>
	<div class="span8">
	<h1>Change Site-Wide settings</h1>
	<% if params[:notice] %>
		<p><font color="red"><%= params[:notice] %></font></p>
	  <% end %>
	<%= render 'form' %>
</div>
<div class="span1">&nbsp;</div><div class="span1">&nbsp;</div>
<%= render 'layouts/footer' %>

app/views/site_settings/index.html.erb
<h1>Listing site_settings</h1>

<table>
  <tr>
    <th>Caching</th>
    <th>Site name</th>
    <th>Time zone</th>
    <th>Left sidebar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @site_settings.each do |site_setting| %>
  <tr>
    <td><%= site_setting.caching %></td>
    <td><%= site_setting.site_name %></td>
    <td><%= site_setting.time_zone %></td>
    <td><%= site_setting.left_sidebar %></td>
    <td><%= link_to 'Show', site_setting %></td>
    <td><%= link_to 'Edit', edit_site_setting_path(site_setting) %></td>
    <td><%= link_to 'Destroy', site_setting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Site setting', new_site_setting_path %>

app/views/site_settings/new.html.erb
<h1>New site_setting</h1>

<%= render 'form' %>

<%= link_to 'Back', site_settings_path %>

app/views/site_settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Caching:</b>
  <%= @site_setting.caching %>
</p>

<p>
  <b>Site name:</b>
  <%= @site_setting.site_name %>
</p>

<p>
  <b>Time zone:</b>
  <%= @site_setting.time_zone %>
</p>

<p>
  <b>Left sidebar:</b>
  <%= @site_setting.left_sidebar %>
</p>


<%= link_to 'Edit', edit_site_setting_path(@site_setting) %> |
<%= link_to 'Back', site_settings_path %>