config/routes.rb
Davesblog::Application.routes.draw do
  resources :blog_images

  resources :site_settings

  resources :categories

  resources :tags

  match 'blogs/fix_blank_published_dates' => 'blogs#fix_blank_published_dates'
  resources :blogs

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  match '/:id' => 'blogs#show'
  
  match "user/settings" => "user#settings"
  match 'user/update' => 'user#update', :as=>'user/update', :via=>'put'

  

  root :to => 'blogs#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :categorizations
	has_many :blogs, :through => :categorizations, :order => 'created_at DESC'
	
	def to_param
	  "#{id}-#{name.downcase.gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')}"
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_filter :authenticate_user!, :except=> [:index, :show]
	
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    #@category = Category.find(params[:id])
    params[:category]=params[:id]
    @blogs=@blogs=find_posts(params)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul class="nav nav-list">
	<% @categories.each do |category| %>
		<li><%= link_to category.name, category %></li>
	<% end %>
</ul>
<br/>
<% if user_signed_in? && current_user.is_admin == 1 %>
<%= link_to 'New Category', new_category_path %>
<% end %>
<%= render 'layouts/footer' %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% content_for :title, @category.name %>

<%= render :partial=> 'layouts/top_menubar', :locals=> {:categories=> @categories, :current_page=> @category.name} %>

<div class="span1">&nbsp;</div><div class="span1">&nbsp;</div>
<div class="span8">
<p id="notice"><%= notice %></p>

<center><h1>Category name here</h1></center>

<% @blogs.each do |blog| %>
	<% if blog.isdraft == 0 %>
	  <h2><%= link_to blog.title,  '/'+blog.to_param %></h2>
	  <p><%= blog.summary %></p>
    <% else %>
    	<% if current_user && blog.user_id == current_user.id %>
			<h2><i><%= link_to blog.title,  '/'+blog.to_param %> DRAFT</i></h2>
			<p><i><%= blog.summary %></i></p>
			<%= link_to 'Edit', :controller=> 'blogs', :action=>'edit' %>
		<% end %>
    <% end %>
<% end %>

<br />
</div>
<div class="span2">
&nbsp;
</div>

<%= render 'layouts/footer' %>