config/routes.rb
Davesblog::Application.routes.draw do
  resources :blog_images

  resources :site_settings

  resources :categories

  resources :tags

  match 'blogs/fix_blank_published_dates' => 'blogs#fix_blank_published_dates'
  resources :blogs

  devise_for :users, :controllers => {:registrations => "registrations"}
  
  match '/:id' => 'blogs#show'
  
  match "user/settings" => "user#settings"
  match 'user/update' => 'user#update', :as=>'user/update', :via=>'put'

  

  root :to => 'blogs#index'

end

app/models/blog_image.rb
class BlogImage < ActiveRecord::Base
has_attached_file :image,
    :styles => {:bs_thumb => ["360x268#", :jpg], 
                :bs_med_thumb => ["260x180#", :jpg],
                :bs_small_thumb => ["160x120#", :jpg]
                }
  #validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 5.megabytes, :message => 'file size maximum 5 MB allowed'
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/bmp', 'image/pjpeg', 'image/x-png']
end

app/controllers/blog_images_controller.rb
class BlogImagesController < ApplicationController
  # GET /blog_images
  # GET /blog_images.json
  
  before_filter :authenticate_user!
  
  def index
    @blog_images = BlogImage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blog_images }
    end
  end

  # GET /blog_images/1
  # GET /blog_images/1.json
  def show
    @blog_image = BlogImage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog_image }
    end
  end

  # GET /blog_images/new
  # GET /blog_images/new.json
  def new
    @blog_image = BlogImage.new
	@blog_image.user_id=current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog_image }
    end
  end

  # GET /blog_images/1/edit
  def edit
    @blog_image = BlogImage.find(params[:id])
    @blog_image.user_id=current_user.id
  end

  # POST /blog_images
  # POST /blog_images.json
  def create
    @blog_image = BlogImage.new(params[:blog_image])
	@blog_image.user_id=current_user.id
    respond_to do |format|
      if @blog_image.save
        format.html { redirect_to @blog_image, notice: 'Blog image was successfully created.' }
        format.json { render json: @blog_image, status: :created, location: @blog_image }
      else
        format.html { render action: "new" }
        format.json { render json: @blog_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blog_images/1
  # PUT /blog_images/1.json
  def update
    @blog_image = BlogImage.find(params[:id])
	@blog_image.user_id=current_user.id
    respond_to do |format|
      if @blog_image.update_attributes(params[:blog_image])
        format.html { redirect_to @blog_image, notice: 'Blog image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_images/1
  # DELETE /blog_images/1.json
  def destroy
    @blog_image = BlogImage.find(params[:id])
    @blog_image.destroy

    respond_to do |format|
      format.html { redirect_to blog_images_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blog_images_helper.rb
module BlogImagesHelper
end

app/views/blog_images/_form.html.erb
<%= form_for(@blog_image,:html => { :multipart => true }) do |f| %>
  <% if @blog_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_image.errors.count, "error") %> prohibited this blog_image from being saved:</h2>

      <ul>
      <% @blog_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_file_name %><br />
    <%= f.text_field :image_file_name %>
  </div>
  <div class="field">
    <%= f.label :image_content_type %><br />
    <%= f.text_field :image_content_type %>
  </div>
  <div class="field">
    <%= f.label :image_file_size %><br />
    <%= f.text_field :image_file_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <%= f.label 'Image' %><br />
  <%= f.file_field :image %>
<% end %>

app/views/blog_images/edit.html.erb
<h1>Editing blog_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_image %> |
<%= link_to 'Back', blog_images_path %>

app/views/blog_images/index.html.erb
<h1>Listing blog_images</h1>

<table>
  <tr>
  	<th></th>
    <th>Image file name</th>
    <th>Image content type</th>
    <th>Image file size</th>
    <th>ID</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog_images.each do |blog_image| %>
  <tr>
  	<td><%= image_tag blog_image.image.url(:bs_small_thumb) %></td>
    <td><%= blog_image.image_file_name %></td>
    <td><%= blog_image.image_content_type %></td>
    <td><%= blog_image.image_file_size %></td>
    <td><%= blog_image.id %></td>
    <td><%= link_to 'Show', blog_image %></td>
    <td><%= link_to 'Edit', edit_blog_image_path(blog_image) %></td>
    <td><%= link_to 'Destroy', blog_image, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blog image', new_blog_image_path %>

app/views/blog_images/new.html.erb
<h1>New blog_image</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_images_path %>

app/views/blog_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image file name:</b>
  <%= @blog_image.image_file_name %>
</p>

<p>
  <b>Image content type:</b>
  <%= @blog_image.image_content_type %>
</p>

<p>
  <b>Image file size:</b>
  <%= @blog_image.image_file_size %>
</p>


<%= link_to 'Edit', edit_blog_image_path(@blog_image) %> |
<%= link_to 'Back', blog_images_path %>